### ISSUE TITLE
Clusterroles used for prometheus access not functional on app-sre cluster

### ISSUE THREAD

**Issue by pbergene** [openshift/telemeter#123]
The clusterroles used for app-sre cluster do not seem to grant prometheus access.  The templated ones including the explicit namespace reference into resourceNames do not work for authz.  This can be verified using the developer accounts in stage and is a blocker for QE and migrating the production environment.

cc @jfchevrette @s-urbaniak @squat @juzhao

```
  resourceNames:
  - <namespace>
  resources:
  - namespaces
  verbs:
  - get
```
