### ISSUE TITLE
double amount of metrics when using the /federate endpoint of infogw

### ISSUE THREAD

**Issue by durandom** [openshift/telemeter#151]
This is the amount of metrics in the infogw cluster:
![image](https://user-images.githubusercontent.com/161888/55258771-1a1fa700-5264-11e9-9f61-ea4727cdb0a1.png)

Here's the same query at my prometheus that /federates from infogw
![image](https://user-images.githubusercontent.com/161888/55258737-0116f600-5264-11e9-9353-b56efcc42dda.png)

In the first half, I had the `scrape_interval` at 60s, which resulted in almost exactly the double amount of datapoints.
The second half had 270s, with those spikes again.

Maybe https://github.com/openshift/telemeter/pull/145 did not have the desired effect?

Indeed I'm getting the metrics twice: ?!

![image](https://user-images.githubusercontent.com/161888/55259364-c57d2b80-5265-11e9-9c4c-05464538bade.png)

Any ideas @s-urbaniak 

Here's the config

```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: prometheus
    replica: $(HOSTNAME)
rule_files:
- /etc/prometheus/*.rules
scrape_configs:
- job_name: telemeter
  honor_labels: true
  params:
    match[]:
    - '{_id!=""}'
  scrape_interval: 1m
  scrape_timeout: 59s
  metrics_path: /federate
  scheme: https
  static_configs:
  - targets:
    - infogw-data.api.openshift.com
  bearer_token: <secret>
```
